
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::136337412157:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-0OFvMPP1Cx6b
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::136337412157:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-03T04:52:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1194"
  uid: 7fae3315-3b2d-4d91-9e54-2f6bb5dc6415
